version: '3.4'

services:
  matchme.candidatesapi:
    image: ${DOCKER_REGISTRY-}matchmecandidatesapi
    build:
      context: .
      dockerfile: ../MatchMe.Candidates/MatchMe.Candidates.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  matchme.opportunitiesapi:
    image: ${DOCKER_REGISTRY-}matchmeopportunitiesapi
    build:
      context: .
      dockerfile: ../MatchMe.Opportunities/MatchMe.Opportunities.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  matchme.matchapi:
    image: ${DOCKER_REGISTRY-}matchmematchapi
    build:
      context: .
      dockerfile: ../MatchMe.Match/MatchMe.Match.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"